spring:
  aop:
    proxy-target-class: false

  datasource:
    url: jdbc:postgresql://sbrd1zb1apfbp0brscomm001.postgres.database.azure.com:5432/pgds333?sslmode=require
    username: svc_d_bp_01
    password: "hp?1k3AS6Cj@S?@3"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.use_sql_comments: true
      hibernate.format_sql: false
    hibernate:
      ddl-auto: none  # 'validate'

  main:
    banner-mode: 'console'
  application:
    name: "gln-back-arsenal-backend-archetype-base"
    version: "3.10.0"
    description: "Archetype for generating Arsenal applications"
  jackson:
    default-property-inclusion: NON_NULL
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${HOST_RHSSO}/auth/realms/${RHSSO_REALM}/protocol/openid-connect/certs

info:
  app:
    groupId: "com.santander.ars"
    artifactId: "gln-back-arsenal-backend-archetype-base"
    version: "3.10.0"
    java.version: "17.0.7"

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /ars-pricing-tax-v1

azure:
  cosmos:
    uri: ${DATABASE_URL:https://sbrd1zb1cdbbp0brscomm002.documents.azure.com:443/}
    key: ${DATABASE_KEY:rN3Biqi2aRXf8g50RswQzpYpJWQE51295bQe1kn4MVBYgKhCnLN06HFl3SZnPtX49wnKzZiVVlTHACDbY21hlg==}
    database: ${DATABASE_NAME:bp}
    connectionType: ${CONNECTION_TYPE:KEY}
    queryMetricsEnabled: false

arsenal:
  library:
    altair:
      personado: false
      altair-user: ${ALTAIR_MQ_USER}
      altair-config:
      format-classpath: com.santander.bp.model.altair
      message-format: PS7
      psFormatEnum: PS7
      useHeaderPs: false
      channel: ${ALTAIR_MQ_CHANNEL}
      message-expired-timeout: 60000
      receive-timeout: 60000
      request-queue: ${ALTAIR_MQ_QUEUE_REQUEST_NAME}
      response-queue: ${ALTAIR_MQ_QUEUE_RESPONSE_NAME}
      server:
        hostname: ${ALTAIR_MQ_QUEUE_SERVER_HOSTNAME}
        port: ${ALTAIR_MQ_QUEUE_SERVER_PORT:1414}
        channel: ${ALTAIR_MQ_CHANNEL}
        username: username
        pwd: password
    core:
      api:
        enable-docs: true
        docs-base-package: com.santander.gt.ngt.controller
        archetypekey: ####415253454E414C####

logging:
  level:
    org.springframework: DEBUG
    com.altec: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: WARN
    spring: INFO
    app: INFO
    servlet: WARN
    web: WARN
    data: INFO

resilience4j:
  ratelimiter:
    instances:
      appArsenalController:
        limitForPeriod: 100
        limitRefreshPeriod: 1000ms
        timeoutDuration: 2000ms
  timelimiter:
    instances:
      appArsenalController:
        timeoutDuration: 2s
  circuitbreaker:
    instances:
      myNewService:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5000ms

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

cucumber:
  publish:
    quiet: true
