# Spring Boot application properties
spring:
  main:
    banner-mode: console

# server port
server:
  port: 8080
    
# Arsenal core library settings
arsenal:
  library:
    core:
      api:
        enable-docs: true # Enable Swagger/OpenAPI documentation
        docs-base-package: com.santander.bp.controller
        archetypekey: ####415253454E414C####
  logging:
    console-log: true
    dev-mode: true
    isGluon: false

# Logging
# Níveis de Log para Depuração
logging:
  level:
    # Nível geral da sua aplicação
    com.santander.bp: DEBUG
    
    # Logs do RestTemplate do Spring
    org.springframework.web.client.RestTemplate: DEBUG
    
    # === ADIÇÃO PARA VER O JSON ===
    # 'headers' mostra os cabeçalhos exatos da requisição e resposta.
    org.apache.http.headers: DEBUG
    # 'wire' é o mais poderoso. Ele mostra o tráfego de rede bruto,
    # incluindo o corpo (body) exato do JSON que recebemos na resposta.
    org.apache.http.wire: TRACE

    # Níveis padrão para os outros pacotes
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    data: WARN

# Resilience4j settings
resilience4j:
  ratelimiter:
    instances:
      appArsenalController:
        limitForPeriod: 100
        limitRefreshPeriod: 1000ms
        timeoutDuration: 2000ms
  timelimiter:
    instances:
      appArsenalController:
        timeoutDuration: 2s

# Health default configurations
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true