# Adicione esta seção ao seu arquivo application.yml
# para externalizar a URL do serviço de pricing.
services:
  pricing:
    url: https://prc-varejo.paas.santanderbr.pre.corp/prc-pricing-investments-adapter/v1/fixed_income_investment_operations/prices

spring:
  aop:
    proxy-target-class: false

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/default_db?sslmode=disable}  # Valor padrão para o PostgreSQL
    username: ${POSTGRES_USER:default_user}  # Valor padrão de usuário
    password: ${POSTGRES_PASSWORD:default_password}  # Valor padrão de senha
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate.use_sql_comments: true
      hibernate.format_sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Define o dialect explicitamente

  main:
    banner-mode: 'console'

  application:
    name: "gln-back-arsenal-backend-archetype-base"
    version: "3.10.0"
    description: "Archetype for generating Arsenal applications"

  jackson:
    default-property-inclusion: NON_NULL

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${HOST_RHSSO:https://localhost/auth/realms/default/protocol/openid-connect/certs}

info:
  app:
    groupId: "com.santander.ars"
    artifactId: "gln-back-arsenal-backend-archetype-base"
    version: "3.10.0"
    java.version: "17.0.7"

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
    context-path: /pricing-tax

azure:
  cosmos:
    uri: ${DATABASE_URL:https://localhost:443/}  # Valor padrão para CosmosDB URI
    key: ${DATABASE_KEY:default_key}  # Chave padrão para CosmosDB
    database: ${DATABASE_NAME:default_db}  # Nome do banco padrão
    connectionType: ${CONNECTION_TYPE:KEY}  # Tipo de conexão padrão
    queryMetricsEnabled: false

arsenal:
  library:
    altair:
      personado: false
      altair-user: ${ALTAIR_MQ_USER:default_user}
      altair-config:
      format-classpath: com.santander.bp.model.altair
      message-format: PS7
      psFormatEnum: PS7
      useHeaderPs: false
      channel: ${ALTAIR_MQ_CHANNEL:default_channel}
      message-expired-timeout: 60000
      receive-timeout: 60000
      request-queue: ${ALTAIR_MQ_QUEUE_REQUEST_NAME:default_request_queue}
      response-queue: ${ALTAIR_MQ_QUEUE_RESPONSE_NAME:default_response_queue}
      server:
        hostname: ${ALTAIR_MQ_QUEUE_SERVER_HOSTNAME:localhost}
        port: ${ALTAIR_MQ_QUEUE_SERVER_PORT:1414}
        channel: ${ALTAIR_MQ_CHANNEL:default_channel}
        username: username
        pwd: password
    core:
      api:
        enable-docs: true
        docs-base-package: com.santander.gt.ngt.controller
        archetypekey: ####415253454E414C####

logging:
  level:
    org.springframework: DEBUG
    com.santander.bp: DEBUG
    com.altec: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: WARN
    spring: INFO
    app: INFO
    servlet: WARN
    web: WARN
    data: INFO

resilience4j:
  ratelimiter:
    instances:
      appArsenalController:
        limitForPeriod: 100
        limitRefreshPeriod: 1000ms
        timeoutDuration: 2000ms
  timelimiter:
    instances:
      appArsenalController:
        timeoutDuration: 2s
  circuitbreaker:
    instances:
      myNewService:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5000ms

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

cucumber:
  publish:
    quiet: true