openapi: 3.0.1
info:
  title: Offer and Pricing Service
  description: Responsible for managing fixed income investment operations, searching for offers and rates
  version: 1.0.0
  contact:
    email: "X311187@prservicos.com.br"
  license:
    name: "Apache"
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: /bp_offer_pricing
tags:
  - name: Offers and Rates
    description: Self-Issued Fixed Income Investment products
paths:
  /offers:
    post:
      tags:
        - Offers and Rates
      summary: "Fetches investment offers and associated fees for fixed income products, returning combined data."
      description: "This endpoint retrieves offers and their associated fees. The returned data is combined to provide a complete view of available investment options based on customer and market segment."
      requestBody:
        description: "Data to be received for retrieving offers and fees"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OffersPricingRequest'
        required: true
      responses:
        '200':
          description: "Successful retrieval of offers and fees"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWrapper'
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '503':
          description: "Service Unavailable."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                  - code: "ERR007"
                    message: "Service unavailable"
                    level: "error"
                    description: "The service is temporarily unavailable."
        '504':
          description: "Gateway timeout."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                  - code: "ERR008"
                    message: "Gateway timeout"
                    level: "error"
                    description: "The request timed out while waiting for a response."
components:
  schemas:
    OffersPricingRequest:
      type: object
      required:
        - documentType
        - customerId
        - documentNumber
      properties:
        documentType:
          type: string
          description: "Document type."
          example: "CPF"
        customerId:
          type: string
          description: "Customer ID."
          example: "123456"
        documentNumber:
          type: string
          description: "Document number."
          example: "34034505445"
        segment:
          type: string
          description: "Customer market segment."
          example: "12"
        channel:
          type: string
          description: "Request channel."
          example: "77"
        centerId:
          type: string
          description: "Center ID (Agency)."
          example: "0025"
        productFamily:
          type: string
          description: "Product family name (e.g., CDB)."
          example: "CDB"
        indicatorRecall:
          type: string
          description: "Indicator of realization (Indicador de Rechamada)."
          example: "Y"
        cdRecall:
          type: string
          description: "Real product code (Código do Produto da Rechamada)."
          example: "26"
        subProductRecall:
          type: string
          description: "Real subproduct code (Código do Subproduto da Rechamada)."
          example: "0103"
        funcType:
          type: string
          description: "Type of functionality for Application or Rescue"
          example: "R"
        subProduct:
          type: string
          description: "By-product chosen in the offer"
          example: "LCI - Invest"
    OffersPricingResponse:
      type: object
      description: "Response object containing investment offer details and pricing information."
      properties:
        id:
          type: string
          description: "Unique identifier for the offer."
          example: "12345"
        product:
          type: string
          description: "Investment product name."
          example: "CDB"
        subProductCode:
          type: string
          description: "Investment sub-product code."
          example: "0003"
        subProduct:
          type: string
          description: "Investment sub-product description."
          example: "LCI - Invest"
        family:
          type: string
          description: "Family code of the investment product."
          example: "CDB"
        term:
          type: integer
          description: "Investment term in days."
          example: 365
        rate:
          type: number
          format: double
          description: "Rate applied to the investment offer."
          example: 12.50
        rateTerm:
          type: array
          description: "List of applicable rates and their respective terms."
          items:
            type: object
            properties:
              term:
                type: integer
                description: "Term in days."
                example: 180
              rate:
                type: number
                format: double
                description: "Rate applied for this term."
                example: 11.75
        minApplicationValue:
          type: number
          format: double
          description: "Minimum investment amount required."
          example: 1000.00
        minRedemptionValue:
          type: number
          format: double
          description: "Minimum amount allowed for redemption."
          example: 500.00
        minBalance:
          type: number
          format: double
          description: "Minimum balance required after redemption."
          example: 100.00
        closingFee:
          type: number
          format: double
          description: "Encumbrance fee applied to the offer."
          example: 0.5
        receivingFee:
          type: number
          format: double
          description: "Fee applied when receiving the investment."
          example: 0.3
        feeDescription:
          type: string
          description: "Description of the fees applied."
          example: "Management and custody fees."
        campaign:
          type: string
          description: "Associated investment campaign, if applicable."
          example: "High-Yield Bonds Promo"
        funding:
          type: number
          format: double
          description: "Total funding allocated to this investment offer."
          example: 5000000.00
        reason:
          type: string
          description: "Reason associated with the offer."
          example: "Special Promotion"
        messages:
          type: array
          description: "List of additional messages related to the offer."
          items:
            type: string
          example: ["Limited-time offer", "Available for VIP customers only"]

    ResponseWrapper:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OffersPricingResponse'
          description: "List of offers and pricing responses"
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: "List of errors"
          example: []
    Errors:
      type: object
      description: "Data structure containing the details for errors."
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: "Array of errors."
    Error:
      type: object
      description: "Data structure containing the error details."
      required:
        - code
        - message
        - level
      properties:
        code:
          type: string
          description: "Unique alphanumeric human-readable error code."
          example: "ERR001"
        message:
          type: string
          description: "Brief summary of the reported issue."
          example: "Invalid Action"
        level:
          $ref: '#/components/schemas/ErrorLevel'
        description:
          type: string
          description: "Detailed description of the reported issue."
          example: "The request parameter is invalid."
    ErrorLevel:
      type: string
      description: "Level of the reported issue."
      enum:
        - INFO
        - WARNING
        - ERROR
      example: "ERROR"
  responses:
    NoContent:
      description: "No content."
    Unauthorized:
      description: "Unauthorized."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR002"
                message: "Unauthorized access"
                level: "error"
                description: "You do not have permission to access this resource."
    Forbidden:
      description: "Forbidden."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR003"
                message: "Forbidden access"
                level: "error"
                description: "Access to this resource is forbidden."
    BadRequest:
      description: "Bad Request."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR004"
                message: "Invalid request"
                level: "error"
                description: "The request parameters are invalid."
    NotFound:
      description: "Not Found."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR005"
                message: "Resource not found"
                level: "error"
                description: "The requested resource was not found."
    InternalServerError:
      description: "Server Error."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR006"
                message: "Internal server error"
                level: "error"
                description: "An unexpected error occurred on the server."
    ServiceUnavailable:
      description: "Service Unavailable."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR007"
                message: "Service unavailable"
                level: "error"
                description: "The service is temporarily unavailable."
    GatewayTimeout:
      description: "Gateway timeout."
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
              - code: "ERR008"
                message: "Gateway timeout"
                level: "error"
                description: "The request timed out while waiting for a response."