openapi: 3.0.1
info:
  title: Offer and Pricing Service
  description: Responsible for managing fixed income investment operations, searching for offers and rates
  version: 1.0.0
  contact:
    email: "X311187@prservicos.com.br"
  license:
    name: "Apache"
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: /api
tags:
  - name: Offers and Rates
    description: Self-Issued Fixed Income Investment products
paths:
  /offers:
    post:
      tags:
        - Offers and Rates
      summary: "Fetches investment offers and associated fees for fixed income products, returning combined data."
      description: "This endpoint retrieves offers and their associated fees. The returned data is combined to provide a complete view of available investment options based on customer and market segment."
      requestBody:
        description: "Data to be received for retrieving offers and fees"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OffersPricingRequest'
        required: true
      responses:
        '200':
          description: "Successful retrieval of offers and fees"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWrapper'
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '503':
          description: "Service Unavailable."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        '504':
          description: "Gateway timeout."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
components:
  schemas:
    OffersPricingRequest:
      type: object
      required:
        - documentType
        - documentNumber
        - customerId
        - segment
        - channel
      properties:
        documentType:
          type: string
          example: "CPF"
        customerId:
          type: string
          example: "123456"
        documentNumber:
          type: string
          example: "34034505445"
        segment:
          type: string
          example: "12"
        channel:
          type: string
          example: "77"
        centerId:
          type: string
          example: "0025"
        productFamily:
          type: string
          example: "CDB"
        indicatorRecall:
          type: string
          example: "Y"
        cdRecall:
          type: string
          example: "26"
        subProductRecall:
          type: string
          example: "0103"
        funcType:
          type: string
          example: "R"
        subProduct:
          type: string
          example: "LCI - Invest"
        companyCode:
          type: string
          example: "033"
          description: "Código da empresa (ex: Santander = 033)."
        creationApp:
          type: string
          example: "BP"
          description: "Sistema de origem da requisição."
        pricingTypeCode:
          type: string
          example: "R1"
          description: "Tipo de precificação (ex: R1, R2)."
        currencyCode:
          type: string
          example: "BRL"
          description: "Código da moeda."
    ResponseWrapper:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OffersPricingResponse'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: "List of errors"
          example: []
    OffersPricingResponse:
      type: object
      properties:
        product:
          type: string
          example: "26"
        subProductCode:
          type: string
          example: "0413"
        subProduct:
          type: string
          example: "LCI 90 DIAS"
        family:
          type: string
          example: "LCI"
        term:
          type: integer
          example: 0
        rateTerm:
          type: array
          items:
            $ref: '#/components/schemas/RateTerm'
        minApplicationValue:
          type: number
          format: double
          example: 1000.0
        minRedemptionValue:
          type: number
          format: double
          example: 100.0
        minBalance:
          type: number
          format: double
          example: 100.0
        closingFee:
          type: number
          format: double
          example: 88.89
        receivingFee:
          type: number
          format: double
          example: 105.0
        feeDescription:
          type: string
          example: "88,89% do CDI"
        indexType:
          type: string
          example: "CDI"
        benchmarkIndex:
          type: string
          example: "FM9"
        gracePeriodIndicator:
          type: boolean
          example: true
        gracePeriod:
          format: integer
          example: 12
        progressiveRemunerationIndicator:
          type: boolean
          example: false
        promotionalCode:
          type: string
          example: "PRM001"
        messages:
          type: array
          items:
            type: string
          example: ["Taxa fora do intervalo", "Cliente na whitelist"]
        investmentPriceProposals:
          type: array
          items:
            $ref: '#/components/schemas/InvestmentPriceProposal'
        legacyFlags:
          type: object
          properties:
            otrPraz:
              type: string
              example: "S"
            inApli:
              type: string
              example: "S"
            inResg:
              type: string
              example: "S"
            agnFutu:
              type: string
              example: "S"
            agnResg:
              type: string
              example: "S"
            hronlin:
              type: string
              example: "20:10:00"
    RateTerm:
      type: object
      properties:
        term:
          type: integer
          example: 90
        rate:
          type: number
          format: double
          example: 88.89
    InvestmentPriceProposal:
      type: object
      properties:
        price:
          type: object
          properties:
            code:
              type: integer
              example: 1234
            priceConceptId:
              type: string
              example: "PCID001"
            tiers:
              type: array
              items:
                type: object
                properties:
                  termInDays:
                    type: integer
                    example: 90
                  aprPercentage:
                    type: string
                    example: "88.89"
        product:
          type: object
          properties:
            name:
              type: string
              example: "LCI 90 DIAS"
            subproduct:
              type: object
              properties:
                code:
                  type: string
                  example: "0413"
        benchmarkIndex:
          type: object
          properties:
            code:
              type: string
              example: "CDI"
        fundingRate:
          type: number
          example: 10.5
        reason:
          type: string
          example: "Campanha promocional"
        promotionalCode:
          type: object
          properties:
            promotionId:
              type: string
              example: "PROMO2025"
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
        - code
        - message
        - level
      properties:
        code:
          type: string
          example: "ERR001"
        message:
          type: string
          example: "Invalid Action"
        level:
          $ref: '#/components/schemas/ErrorLevel'
        description:
          type: string
          example: "The request parameter is invalid."
    ErrorLevel:
      type: string
      enum:
        - INFO
        - WARNING
        - ERROR
      example: "ERROR"